#include "dlss5.h"
#include <cuda.h>
#include <windows.h>
#include <vector>
#include <string>
#include <iostream>
#include <fstream>
#include <stdexcept>
#include <chrono>
#include <cmath>
#include <filesystem>
void ck(D5Status code){if(code)throw std::runtime_error(std::string(d5_last_error()));}
void cu(CUresult code){if(code){const char*p=nullptr;cuGetErrorString(code,&p);throw std::runtime_error(p?p:"CUDA failed");}}
D5Tensor view(CUdeviceptr p,unsigned w,unsigned h,unsigned c,unsigned layout=D5_HWC){return {sizeof(D5Tensor),D5_F32,layout,c,w,h,p,layout==D5_HWC?uint64_t(w)*c*4:uint64_t(w)*4,layout==D5_CHW?uint64_t(w)*h*4:0};}
D5Status D5_CALL custom_output(void*user,const D5StageInvocation*inv){++*(int*)user;if(inv->stage!=D5_STAGE_OUTPUT||inv->input_count<4||inv->output_count!=1)return D5_INVALID_ARGUMENT;const auto&in=inv->inputs[3];const auto&out=inv->outputs[0];CUDA_MEMCPY2D copy{};copy.srcMemoryType=copy.dstMemoryType=CU_MEMORYTYPE_DEVICE;copy.srcDevice=in.data;copy.dstDevice=out.data;copy.srcPitch=in.row_stride_bytes;copy.dstPitch=out.row_stride_bytes;copy.WidthInBytes=size_t(in.width)*3*4;copy.Height=in.height;return cuMemcpy2DAsync(&copy,(CUstream)inv->cuda_stream)==CUDA_SUCCESS?D5_OK:D5_CUDA_ERROR;}
void shared_runtime(){
 std::wstring path(32768,L'\0');auto n=GetModuleFileNameW(nullptr,path.data(),(DWORD)path.size());path.resize(n);auto exe=std::filesystem::path(path).parent_path();auto root=exe.parent_path().parent_path()/"runtime";
 if(std::filesystem::is_directory(root/"bin")){
  SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_DEFAULT_DIRS|LOAD_LIBRARY_SEARCH_USER_DIRS);AddDllDirectory((root/"bin").c_str());
  auto ort=root/"bin/onnxruntime.dll";if(std::filesystem::is_regular_file(ort)&&!LoadLibraryExW(ort.c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_DEFAULT_DIRS))throw std::runtime_error("Cannot load shared runtime ONNX library");
  auto has_value=[](const wchar_t* name){wchar_t value[2]{};return GetEnvironmentVariableW(name,value,2)!=0;};if(!has_value(L"NATIVE_NR_TOOLCHAIN")&&!has_value(L"DLSS5_FP8_TOOLCHAIN"))_wputenv_s(L"NATIVE_NR_TOOLCHAIN",(root/"cuda12.8").c_str());
 }
}
int main(int argc,char**argv){try{shared_runtime();if(argc<2){std::cout<<"d5_consumer MODEL_DIR [packet.f32 H W output.f32]\n";return 0;}D5Config cfg;d5_default_config(&cfg);cfg.model_directory_utf8=argv[1];bool full=argc>2&&std::string(argv[2])=="--full";bool validate=argc>2&&std::string(argv[2])=="--validate";if(validate)cfg.enabled_stages=0;if(full)cfg.enabled_stages=D5_ENABLE_DEPTH|D5_ENABLE_FLOW|D5_ENABLE_GUIDE|D5_ENABLE_RECONSTRUCT|D5_ENABLE_NR;D5Session session=nullptr;ck(d5_create(&cfg,&session));CUdevice device;CUcontext context;cu(cuDeviceGet(&device,0));cu(cuDevicePrimaryCtxRetain(&context,device));cu(cuCtxPushCurrent(context));CUstream stream;cu(cuStreamCreate(&stream,CU_STREAM_NON_BLOCKING));
 if(argc>=6){unsigned h=std::stoul(argv[3]),w=std::stoul(argv[4]);std::vector<float>packet(size_t(w)*h*16);std::ifstream f(argv[2],std::ios::binary);if(!f.read((char*)packet.data(),packet.size()*4))throw std::runtime_error("Cannot read exact packet");CUdeviceptr p,o;cu(cuMemAlloc(&p,packet.size()*4));cu(cuMemAlloc(&o,size_t(w)*h*16));cu(cuMemcpyHtoD(p,packet.data(),packet.size()*4));auto input=view(p,w,h,16,D5_CHW),output=view(o,w,h,4);auto tick=std::chrono::steady_clock::now();ck(d5_prepare_packet(session,w,h));std::cout<<"prepare_seconds="<<std::chrono::duration<double>(std::chrono::steady_clock::now()-tick).count()<<"\n";tick=std::chrono::steady_clock::now();ck(d5_infer_packet(session,&input,&output,stream));ck(d5_synchronize(session));std::cout<<"infer_seconds="<<std::chrono::duration<double>(std::chrono::steady_clock::now()-tick).count()<<"\n";std::vector<float>result(size_t(w)*h*4);cu(cuMemcpyDtoH(result.data(),o,result.size()*4));std::ofstream out(argv[5],std::ios::binary);out.write((char*)result.data(),result.size()*4);cu(cuMemFree(p));cu(cuMemFree(o));
 }else{
 const unsigned w=full?640:320,h=full?360:320;std::vector<float>rgb(size_t(w)*h*3);for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x){auto i=(size_t(y)*w+x)*3;rgb[i]=float(x)/(w-1);rgb[i+1]=float(y)/(h-1);rgb[i+2]=.25f;}
 CUdeviceptr p,o;cu(cuMemAlloc(&p,rgb.size()*4));cu(cuMemAlloc(&o,rgb.size()*4));cu(cuMemcpyHtoD(p,rgb.data(),rgb.size()*4));D5Frame frame{};frame.struct_size=sizeof(frame);frame.reset=1;frame.cuda_stream=stream;frame.color=view(p,w,h,3);frame.output=view(o,w,h,3);frame.delta_ms=16.6667f;ck(d5_prepare(session,w,h));if(validate){auto original=frame.color.data;frame.color.data=(uint64_t)rgb.data();if(d5_process(session,&frame)!=D5_INVALID_ARGUMENT)throw std::runtime_error("Host pointer was not rejected");frame.color.data=original;std::cout<<"host_pointer_rejection_OK\n";}ck(d5_process(session,&frame));ck(d5_synchronize(session));D5Tensor borrowed{};borrowed.struct_size=sizeof(borrowed);ck(d5_stage_output(session,D5_STAGE_OUTPUT,0,&borrowed));if(borrowed.data!=o||borrowed.width!=w||borrowed.height!=h)throw std::runtime_error("Borrowed stage view mismatch");std::vector<float>result(rgb.size());cu(cuMemcpyDtoH(result.data(),o,result.size()*4));for(auto v:result)if(!std::isfinite(v))throw std::runtime_error("Nonfinite NR image");std::ofstream("consumer-output.f32",std::ios::binary).write((char*)result.data(),result.size()*4);
 if(full){for(int i=1;i<4;++i){for(unsigned y=0;y<h;++y)for(unsigned x=0;x<w;++x){auto offset=(size_t(y)*w+x)*3;rgb[offset]=float((x+i*3)%w)/(w-1);rgb[offset+1]=float(y)/(h-1);rgb[offset+2]=.25f;}cu(cuMemcpyHtoD(p,rgb.data(),rgb.size()*4));frame.reset=0;frame.frame_id=i;ck(d5_process(session,&frame));ck(d5_synchronize(session));cu(cuMemcpyDtoH(result.data(),o,result.size()*4));for(auto v:result)if(!std::isfinite(v))throw std::runtime_error("Nonfinite full-pipeline output");}std::cout<<"full_native_vda_raft_guide_fsr_nr_frames=4_OK\n";}
 int calls=0;D5Plugin plugin{sizeof(D5Plugin),D5_STAGE_OUTPUT,custom_output,&calls};ck(d5_set_plugin(session,&plugin));ck(d5_process(session,&frame));ck(d5_synchronize(session));cu(cuMemcpyDtoH(result.data(),o,result.size()*4));if(result!=rgb||calls!=1)throw std::runtime_error("Replacement output was not honored");std::cout<<"image_OK replacement_GPU_output_bit_exact=true callback_calls="<<calls<<" nondefault_stream=true\n";cu(cuMemFree(p));cu(cuMemFree(o));
 }
 ck(d5_destroy(session));cu(cuStreamDestroy(stream));CUcontext previous;cu(cuCtxPopCurrent(&previous));cu(cuDevicePrimaryCtxRelease(device));std::cout<<"consumer_OK\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
