"""Development-only extraction of shape-independent address permutations; no model values."""
import ast, base64, json, zlib
from pathlib import Path
import numpy as np
root = Path(__file__).resolve().parents[2]
tree = ast.parse((root / 'reference/dlss5_model.py').read_text(encoding='utf-8'))
assets = next(ast.literal_eval(n.value) for n in tree.body if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == '_EMBEDDED_STATIC_ASSETS' for t in n.targets))
def asset(name):
    return zlib.decompress(base64.b85decode(assets[name]))
permutation = np.frombuffer(asset('tinlayout-1h32-permutation.i32'), '<i4').reshape(64, 32)
inverse = np.empty((2048, 2), np.int32)
for token in range(64):
    for channel in range(32):
        inverse[permutation[token, channel]] = token, channel
qmma = np.empty((64, 32), np.int32)
for tg in range(4):
    for lane in range(32):
        for index in range(16):
            row = lane // 4 if index < 4 or 8 <= index < 12 else lane // 4 + 8
            col = lane % 4 * 4 + (index & 3) + (16 if index >= 8 else 0)
            qmma[tg * 16 + row, col] = tg * 512 + lane * 16 + index
ci = np.argsort(inverse[qmma][0, :, 1])
routing = json.loads(asset('block1-ffn-hidden-routing.json'))
oi = np.argsort([routing['w2_output_n_to_qkv_k'][str(i)][0] for i in range(32)])
text = '// Generated by nr_generate_weight_routes.py from frozen address codecs, not weights.\n#pragma once\nnamespace dlss5::nr::detail {\n'
for name, value in [('channel_inverse', ci), ('post_gate_route', oi[ci])]:
    text += 'inline constexpr int ' + name + '[32]={' + ','.join(map(str, value.tolist())) + '};\n'
text += '}\n'
Path(__file__).with_name('nr_weight_routes.h').write_text(text, encoding='utf-8')
print(text)
