// Generated by nr_generate_weight_routes.py from frozen address codecs, not weights.
#pragma once
namespace dlss5::nr::detail
{
inline constexpr int channel_inverse[32] = {0,  1,  2,  3,  16, 17, 18, 19, 4,  5,  6,
                                            7,  20, 21, 22, 23, 8,  9,  10, 11, 24, 25,
                                            26, 27, 12, 13, 14, 15, 28, 29, 30, 31};
inline constexpr int post_gate_route[32] = {0,  1,  8,  9,  16, 17, 24, 25, 2,  3,  10,
                                            11, 18, 19, 26, 27, 4,  5,  12, 13, 20, 21,
                                            28, 29, 6,  7,  14, 15, 22, 23, 30, 31};
} // namespace dlss5::nr::detail
